### ISSUE TITLE
Live reload doesn't work inside docker

### ISSUE THREAD

**Issue by gen4sp** [jaredpalmer/backpack#156]
Everything works well: after editing a file backpack reloads an app. 
But if I run in under the docker, and source files in a mounted folder - it doesn't work. 
How I can fix it?

```
api:
    build: ./api
    volumes:
        - ./api:/usr/app/
        - /usr/app/node_modules
    environment:
      - SERVER_PORT=4000
      - SERVER_HOST=0.0.0.0
      - NODE_ENV=development
      - DB_PORT=27017
      - DB_HOST=mongo
      - WAIT_HOSTS=mongo:27017
    ports:
      - "4000:4000"
    expose:
      - "4000"
    links:
      - mongo
    working_dir: /usr/app
    command: sh -c "/wait && yarn dev"
```
